### PR TITLE
Package Auto-Discovery support

### PR DESCRIPTION
**Pull request by the94air**

### CODE REVIEW

**Comment by ocano-diego** [comment]
This would be nice

**Comment by the94air** [comment]
He left GitHub for a long time so... I don't expect that he will merge soon :sweat_smile:. You may need to fork this repo for adding this feature.

**Comment by the94air** [comment]
:disappointed:

**Review by datashaman — COMMENTED** [review]
Looks good. :)

**Comment by datashaman** [comment]
@the94air reopen it and i'll merge.

**Comment by the94air** [comment]
@datashaman unfortunately, I am unable to reopen the PR because I removed the fork. Here a new pull request #34.

**Pull request closed without merging**
